namespace Veda.Core;

/// <summary>
/// A single output chunk of a streaming query.
/// type = "sources" carries the source list (sent before the LLM starts answering);
/// type = "token"    carries the token text generated by the LLM;
/// type = "done"     signals the end of the stream and carries the isHallucination result.
/// </summary>
public record RagStreamChunk
{
    /// <summary>Chunk type: sources | token | done</summary>
    public required string Type { get; init; }

    /// <summary>Text fragment output by the LLM (populated when Type = "token").</summary>
    public string? Token { get; init; }

    /// <summary>List of retrieved sources (populated when Type = "sources").</summary>
    public IReadOnlyList<SourceReference>? Sources { get; init; }

    /// <summary>Answer confidence (populated when Type = "done").</summary>
    public float? AnswerConfidence { get; init; }

    /// <summary>Whether a hallucination is suspected (populated when Type = "done").</summary>
    public bool? IsHallucination { get; init; }
}
