namespace Veda.Core.Interfaces;

/// <summary>
/// Second line of defense against hallucinations: LLM self-verification service contract.
/// Uses an additional LLM call to verify sentence by sentence that the answer comes entirely from the retrieved context.
/// Whether it is enabled is controlled by the Veda:Rag:EnableSelfCheckGuard configuration option.
/// </summary>
public interface IHallucinationGuardService
{
    /// <summary>
    /// Verifies that the answer is fully supported by the provided context.
    /// </summary>
    /// <param name="answer">The answer text generated by the LLM.</param>
    /// <param name="context">The retrieved raw document context (output of BuildContext).</param>
    /// <returns>true if the answer is grounded in the documents (no hallucination); false if potential hallucinated content is detected.</returns>
    Task<bool> VerifyAsync(string answer, string context, CancellationToken ct = default);
}
